CREATE TABLE [dbo].[PSACCESSLOG] (
[OPRID] varchar(30) NOT NULL,
[LOGIPADDRESS] varchar() NOT NULL,
[LOGINDTTM] PSDATETIME NULL 
[PT_TRACING_ID] varchar(14) NOT NULL,
[PT_SIGNON_TYPE] varchar(3) NOT NULL,
[LOGOUTDTTM] PSDATETIME NULL
[PT_SIGNOUT_REASON] varchar() NOT NULL